### ISSUE TITLE
.bunFileNotFoundError: /home/username/.bun/bin/bun

### ISSUE THREAD

**Issue by iandresolares** [divin/divingavran#2]
Hello, 
first of all, thank you for the public repo. I am trying to test it on WSL Ubuntu 20.04. The problem is when executing "reflex run" I get the following error: FileNotFoundError: [Errno 2] No such file or directory: '/home/andres/.bun/bin/bun'

I installed node.js and bun manually and setup BUN_INSTALL and PATH env variables but still I get the error. Actually the directory .bun exists but .bun/bin doesn't.

Any idea on how to fix this? Thanks!

**Comment by divin** [comment]
Hi @iandresolares,

Thanks for checking out the repo. I assume you installed `Reflex` via my `requirements.txt`, right? If so, you could try installing the latest version of `Reflex` via `pip` in a new environment, then running `reflex init` and then `reflex run`. If you are lucky, this should fix the problem, as `Reflex` has received several updates since this repo was created. I will also try to update the `requirements.txt` tomorrow.

I recently tried running `Reflex` on WSL and didn't need to install `node.js` or `bun` as these should now be included in the latest version of `Reflex`. You may need to uninstall `bun` and `Node.js` as it may have messed up something in your environment variables.

One note, the only bug I encountered on WSL was an `ASGI error` which I was able to fix by fixing `python-engineio==4.5.1` (basically install `python-engineio-4.5.1` first and then install `Reflex`). However, this should be fixed according to this [issue](https://github.com/reflex-dev/reflex/issues/1658). So you might want to try installing `Reflex` as usual first.

If you still have problems, let me know! :)

Best,
Divin

**Comment by iandresolares** [comment]
Hello @divin,
thank you very much for your response and time. I tried removing the folder completely and cloning it again and trying again. Note I am using pyenv, which I guess it doesn't matter but just in case. 
I did install reflex via your requirements.txt but also tried installing the latest version, same result.

What I realize now is that when doing the `reflex init ` I get: `bun was installed successfully to ~/.reflex/.bun/bin/bun`. But as you can see when executing the `reflex run` it is trying to find bun in another path which doesn't exist. I tried adding this to PATH environment variable but I still get the error.

I guess if I just make reflex try to find bun in the correct path it will work, but can not find how to do that. What do you think?

Best regards,

Andrés

**Comment by divin** [comment]
I guess there is something messed up with the environment variables now and Reflex is confused which path it should use 😄 

> I guess if I just make reflex try to find bun in the correct path it will work, but can not find how to do that. 

Good point, you can do that by adding the `bun_path` to the [`rxconfig.py`](https://github.com/divin/divingavran.com/blob/main/rxconfig.py). It should look something like this:

```python
config = WebsiteConfig(
    app_name="website",
    env=rx.Env.DEV,
    bun_path="~/.reflex/.bun/bin/bun",
)
```

Not sure if Reflex can handle this type of path or if you have to provide the absolute or relative path.
Let me know if this solved the issue :)

**Comment by iandresolares** [comment]
Hi!
Yes that works!!! (with absolute path). Thank you very much!!!

I close the issue!!

Andrés
